modLoader="javafml"
loaderVersion="*"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Screenshot%20Compression"
logoFile="icon.png"

[[mods]]
modId="screenshotcompression"
version="1.4"
displayName="Screenshot Compression"
displayURL="https://serilum.com/mod/screenshot-compression"
authors="Serilum"
description='''Automatically compress screenshots taken in-game to lower file size with various config options.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, AnyankaT, aternosorg, Cherriesaurus, Linda Jansen, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate Appreciate it! <3   
'''

[[dependencies.screenshotcompression]]
    modId="collective"
    type="required"
    versionRange="[8.40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.screenshotcompression]]
    modId="minecraft"
    type="required"
    versionRange="[26.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "screenshotcompression.mixins.json"